// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: offer.proto

package offerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartnerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating float32 `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Orders int64   `protobuf:"varint,4,opt,name=orders,proto3" json:"orders,omitempty"`
}

func (x *PartnerInfo) Reset() {
	*x = PartnerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerInfo) ProtoMessage() {}

func (x *PartnerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_offer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerInfo.ProtoReflect.Descriptor instead.
func (*PartnerInfo) Descriptor() ([]byte, []int) {
	return file_offer_proto_rawDescGZIP(), []int{0}
}

func (x *PartnerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PartnerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartnerInfo) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *PartnerInfo) GetOrders() int64 {
	if x != nil {
		return x.Orders
	}
	return 0
}

type GetOfferStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowId    string `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	CatalogId string `protobuf:"bytes,2,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
}

func (x *GetOfferStreamRequest) Reset() {
	*x = GetOfferStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfferStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferStreamRequest) ProtoMessage() {}

func (x *GetOfferStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferStreamRequest.ProtoReflect.Descriptor instead.
func (*GetOfferStreamRequest) Descriptor() ([]byte, []int) {
	return file_offer_proto_rawDescGZIP(), []int{1}
}

func (x *GetOfferStreamRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *GetOfferStreamRequest) GetCatalogId() string {
	if x != nil {
		return x.CatalogId
	}
	return ""
}

type GetOfferStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Partner *PartnerInfo `protobuf:"bytes,2,opt,name=partner,proto3" json:"partner,omitempty"`
	Amount  int64        `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetOfferStreamResponse) Reset() {
	*x = GetOfferStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfferStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferStreamResponse) ProtoMessage() {}

func (x *GetOfferStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferStreamResponse.ProtoReflect.Descriptor instead.
func (*GetOfferStreamResponse) Descriptor() ([]byte, []int) {
	return file_offer_proto_rawDescGZIP(), []int{2}
}

func (x *GetOfferStreamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOfferStreamResponse) GetPartner() *PartnerInfo {
	if x != nil {
		return x.Partner
	}
	return nil
}

func (x *GetOfferStreamResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetOfferDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOfferDetailsRequest) Reset() {
	*x = GetOfferDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfferDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferDetailsRequest) ProtoMessage() {}

func (x *GetOfferDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetOfferDetailsRequest) Descriptor() ([]byte, []int) {
	return file_offer_proto_rawDescGZIP(), []int{3}
}

func (x *GetOfferDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOfferDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CatalogId string `protobuf:"bytes,2,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	PartnerId string `protobuf:"bytes,3,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	Amount    int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetOfferDetailsResponse) Reset() {
	*x = GetOfferDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfferDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferDetailsResponse) ProtoMessage() {}

func (x *GetOfferDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetOfferDetailsResponse) Descriptor() ([]byte, []int) {
	return file_offer_proto_rawDescGZIP(), []int{4}
}

func (x *GetOfferDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOfferDetailsResponse) GetCatalogId() string {
	if x != nil {
		return x.CatalogId
	}
	return ""
}

func (x *GetOfferDetailsResponse) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *GetOfferDetailsResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpdatePartnerTotalOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdatePartnerTotalOrderRequest) Reset() {
	*x = UpdatePartnerTotalOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartnerTotalOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartnerTotalOrderRequest) ProtoMessage() {}

func (x *UpdatePartnerTotalOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartnerTotalOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartnerTotalOrderRequest) Descriptor() ([]byte, []int) {
	return file_offer_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePartnerTotalOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdatePartnerTotalOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePartnerTotalOrderResponse) Reset() {
	*x = UpdatePartnerTotalOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartnerTotalOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartnerTotalOrderResponse) ProtoMessage() {}

func (x *UpdatePartnerTotalOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartnerTotalOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdatePartnerTotalOrderResponse) Descriptor() ([]byte, []int) {
	return file_offer_proto_rawDescGZIP(), []int{6}
}

type UpdatePartnerRatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating float32 `protobuf:"fixed32,2,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *UpdatePartnerRatingRequest) Reset() {
	*x = UpdatePartnerRatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartnerRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartnerRatingRequest) ProtoMessage() {}

func (x *UpdatePartnerRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartnerRatingRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartnerRatingRequest) Descriptor() ([]byte, []int) {
	return file_offer_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePartnerRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePartnerRatingRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type UpdatePartnerRatingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rating float32 `protobuf:"fixed32,1,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *UpdatePartnerRatingResponse) Reset() {
	*x = UpdatePartnerRatingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartnerRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartnerRatingResponse) ProtoMessage() {}

func (x *UpdatePartnerRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartnerRatingResponse.ProtoReflect.Descriptor instead.
func (*UpdatePartnerRatingResponse) Descriptor() ([]byte, []int) {
	return file_offer_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePartnerRatingResponse) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_offer_proto protoreflect.FileDescriptor

var file_offer_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x22, 0x61, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x4f, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x2e,
	0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x61, 0x72,
	0x74, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x1f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x1a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x22, 0x35, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74,
	0x6e, 0x65, 0x72, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x32, 0x8a, 0x03, 0x0a, 0x05, 0x4f, 0x66,
	0x66, 0x65, 0x72, 0x12, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1e, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x56, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1f, 0x2e,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x6e, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74,
	0x6e, 0x65, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x27, 0x2e,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x62, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74,
	0x6e, 0x65, 0x72, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x2e, 0x6f, 0x66, 0x66, 0x65,
	0x72, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_offer_proto_rawDescOnce sync.Once
	file_offer_proto_rawDescData = file_offer_proto_rawDesc
)

func file_offer_proto_rawDescGZIP() []byte {
	file_offer_proto_rawDescOnce.Do(func() {
		file_offer_proto_rawDescData = protoimpl.X.CompressGZIP(file_offer_proto_rawDescData)
	})
	return file_offer_proto_rawDescData
}

var file_offer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_offer_proto_goTypes = []interface{}{
	(*PartnerInfo)(nil),                     // 0: offerpb.PartnerInfo
	(*GetOfferStreamRequest)(nil),           // 1: offerpb.GetOfferStreamRequest
	(*GetOfferStreamResponse)(nil),          // 2: offerpb.GetOfferStreamResponse
	(*GetOfferDetailsRequest)(nil),          // 3: offerpb.GetOfferDetailsRequest
	(*GetOfferDetailsResponse)(nil),         // 4: offerpb.GetOfferDetailsResponse
	(*UpdatePartnerTotalOrderRequest)(nil),  // 5: offerpb.UpdatePartnerTotalOrderRequest
	(*UpdatePartnerTotalOrderResponse)(nil), // 6: offerpb.UpdatePartnerTotalOrderResponse
	(*UpdatePartnerRatingRequest)(nil),      // 7: offerpb.UpdatePartnerRatingRequest
	(*UpdatePartnerRatingResponse)(nil),     // 8: offerpb.UpdatePartnerRatingResponse
}
var file_offer_proto_depIdxs = []int32{
	0, // 0: offerpb.GetOfferStreamResponse.partner:type_name -> offerpb.PartnerInfo
	1, // 1: offerpb.Offer.GetOfferStream:input_type -> offerpb.GetOfferStreamRequest
	3, // 2: offerpb.Offer.GetOfferDetails:input_type -> offerpb.GetOfferDetailsRequest
	5, // 3: offerpb.Offer.UpdatePartnerTotalOrder:input_type -> offerpb.UpdatePartnerTotalOrderRequest
	7, // 4: offerpb.Offer.UpdatePartnerRating:input_type -> offerpb.UpdatePartnerRatingRequest
	2, // 5: offerpb.Offer.GetOfferStream:output_type -> offerpb.GetOfferStreamResponse
	4, // 6: offerpb.Offer.GetOfferDetails:output_type -> offerpb.GetOfferDetailsResponse
	6, // 7: offerpb.Offer.UpdatePartnerTotalOrder:output_type -> offerpb.UpdatePartnerTotalOrderResponse
	8, // 8: offerpb.Offer.UpdatePartnerRating:output_type -> offerpb.UpdatePartnerRatingResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_offer_proto_init() }
func file_offer_proto_init() {
	if File_offer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_offer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartnerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfferStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfferStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfferDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfferDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePartnerTotalOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePartnerTotalOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePartnerRatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePartnerRatingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_offer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_offer_proto_goTypes,
		DependencyIndexes: file_offer_proto_depIdxs,
		MessageInfos:      file_offer_proto_msgTypes,
	}.Build()
	File_offer_proto = out.File
	file_offer_proto_rawDesc = nil
	file_offer_proto_goTypes = nil
	file_offer_proto_depIdxs = nil
}
